### ISSUE TITLE
 failed for task ':nodejs-download'.

### ISSUE THREAD

**Issue by ardmn** [Kotlin/kotlin-frontend-plugin#52]
when execute:  ```./gradlew :build```
```
Execution failed for task ':nodejs-download'.
> Could not read /IdeaProjects/plugin/build/node-v9.9.0-darwin-x64.tar.gz.
   > java.io.EOFException (no error message)
```

kotlin-frontend-plugin:0.0.30
kotlin_version = '1.2.21'

IntelliJ IDEA 2017.3.5 (Ultimate Edition)
Build #IU-173.4674.33, built on March 5, 2018

JRE: 1.8.0_152-release-1024-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Mac OS X 10.13.3

Can you help please ?

**Comment by vkhikhlov** [comment]
I recently had the same problem. It occurs when a connection is successfully established but there is no content to read from the inputStream, so an empty file is created, which causes this error. It happened when I had a wifi connection, so when I switched to ethernet connection the problem was gone. I think we have to figure out why successful http or https connections can lead to such results. Maybe because of JDK bug or because of network problems?

**Comment by ardmn** [comment]
Yes, I think you are right. I came back to project after a few days and it now works fine .
